### PR TITLE
Update _config.yml with new background image

### PR DESCRIPTION
**Pull request by cwhite92**

### CODE REVIEW

**Comment by svenluijten** [comment]
can the feature branches be deleted after the PR has been merged? Would clean up [the branches view](https://github.com/decahedronio/decahedron.io/branches) a bit :smile:

**Comment by cwhite92** [comment]
good spot 👍

**Comment by svenluijten** [comment]
Just making sure - I'm not too familiar with this protected-branch workflow.

**Comment by cwhite92** [comment]
It actually just means that people can't force push to master, but they can still do a regular push. I'm not bothered if people push directly to master, since we don't need to code review the website :P

**Pull request merged**
